const {SlashCommandBuilder,PermissionFlagsBits}=require('discord.js');const {infoEmbed,successEmbed,errorEmbed}=require('../embeds');const {getConfig,setConfig,resetConfig}=require('../db');const {parseDuration,formatDuration}=require('../utils');
const data=new SlashCommandBuilder().setName('jailconfig').setDescription('Configure Warden.')
.addSubcommand(s=>s.setName('view').setDescription('View configuration.'))
.addSubcommand(s=>s.setName('role').setDescription('Set jail role.').addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true)))
.addSubcommand(s=>s.setName('category').setDescription('Set jail category.').addChannelOption(o=>o.setName('category').setDescription('Category').setRequired(true)))
.addSubcommand(s=>s.setName('logchannel').setDescription('Set log channel.').addChannelOption(o=>o.setName('channel').setDescription('Text channel').setRequired(true)))
.addSubcommand(s=>s.setName('defaulttime').setDescription('Set default sentence.').addStringOption(o=>o.setName('duration').setDescription('Duration').setRequired(true)))
.addSubcommand(s=>s.setName('reset').setDescription('Reset configuration.'));
module.exports={data,async execute(i){if(!i.memberPermissions.has(PermissionFlagsBits.Administrator))return i.reply({embeds:[errorEmbed('You need Administrator permission to run this.')],ephemeral:true});const sub=i.options.getSubcommand();if(sub==='view'){const c=getConfig(i.guild.id);return i.reply({embeds:[infoEmbed('WARDEN CONFIGURATION',null,[['Jail Role',c.jail_role_id?`<@&${c.jail_role_id}>`:'Not configured',true],['Jail Category',c.jail_category_id?`<#${c.jail_category_id}>`:'Not configured',true],['Log Channel',c.log_channel_id?`<#${c.log_channel_id}>`:'Not configured',true],['Default Duration',formatDuration(c.default_seconds),true]])]})}if(sub==='reset'){resetConfig(i.guild.id);return i.reply({embeds:[successEmbed('CONFIGURATION RESET','Warden configuration has been reset to defaults.')]})}if(sub==='role'){const r=i.options.getRole('role');setConfig(i.guild.id,{jail_role_id:r.id});return i.reply({embeds:[successEmbed('CONFIGURATION UPDATED',`Jail role set to ${r}.`)]})}if(sub==='category'){const c=i.options.getChannel('category');setConfig(i.guild.id,{jail_category_id:c.id});return i.reply({embeds:[successEmbed('CONFIGURATION UPDATED',`Jail category set to ${c}.`)]})}if(sub==='logchannel'){const c=i.options.getChannel('channel');setConfig(i.guild.id,{log_channel_id:c.id});return i.reply({embeds:[successEmbed('CONFIGURATION UPDATED',`Log channel set to ${c}.`)]})}try{const s=parseDuration(i.options.getString('duration'));if(s==null)throw new Error('Default duration cannot be permanent.');setConfig(i.guild.id,{default_seconds:s});return i.reply({embeds:[successEmbed('CONFIGURATION UPDATED',`Default jail duration set to **${formatDuration(s)}**.`)]})}catch(e){return i.reply({embeds:[errorEmbed(e.message)],ephemeral:true})}}};
